apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: hama-budget
  name: hama-budget-deployment
  namespace: hama-review-finance-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hama-budget
  template:
    metadata:
      labels:
        app: hama-budget
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: hama-budget-config
              key: JWT_SECRET
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: hama-budget-config
              key: MONGODB_URI
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: hama-budget-config
              key: PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: hama-budget-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: hama-budget-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hama-budget-sec
              key: REDIS_PASSWORD
        image: jangseokhan123/hama-budget:1.0
        name: hama-budget
        ports:
        - containerPort: 3005
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hama-budget
  name: hama-budget-svc
  namespace: hama-review-finance-ns
spec:
  ports:
  - name: hama-budget-svc
    port: 3205
    targetPort: 3005
  selector:
    app: hama-budget
  type: ClusterIP
