apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hama-image-upload
  name: hama-image-upload-deployment
  namespace: hama-image-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hama-image-upload
  template:
    metadata:
      labels:
        app: hama-image-upload
    spec:
      containers:
      - name: hama-image-upload
        env:
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: AWS_REGION
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: AWS_S3_BUCKET_NAME
        - name: JWT_SECRET 
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: JWT_SECRET
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: PORT
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: REDIS_HOST 
        - name: REDIS_PORT 
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: REDIS_PORT
        - name: THUMBNAIL_API_URL
          valueFrom:
            configMapKeyRef:
              name: hama-image-upload-config
              key: THUMBNAIL_API_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: hama-image-upload-sec
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY 
          valueFrom:
            secretKeyRef:
              name: hama-image-upload-sec
              key: AWS_SECRET_ACCESS_KEY
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hama-image-upload-sec
              key: REDIS_PASSWORD
        image: 192.168.2.76:443/hama/hama-image-upload:1.2 
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hama-image-upload
  name: hama-image-upload-svc
  namespace: hama-image-ns
spec:
  ports:
  - port: 3202
    targetPort: 3002
  selector:
    app: hama-image-upload
  type: ClusterIP
