# base/kustomization.yaml
resources:
  - hama-auth-deploy-svc.yaml
  - hama-budget-deploy-svc.yaml
  - hama-chat-deploy-svc.yaml
  - hama-frontend-deploy-svc.yaml
  - hama-image-thumbnail-deploy-svc.yaml
  - hama-image-upload-deploy-svc.yaml
  - hama-ocr-deploy-svc.yaml
  - hama-product-deploy-svc.yaml
  - hama-review-deploy-svc.yaml
  - hama-shoppingcart-deploy-svc.yaml
images:
  - name: 192.168.2.76:443/hama/hama-frontend
    newTag: "latest"  # GitHub Actions가 이 값을 `BUILD_NUMBER`로 업데이트 
